name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/Deploy.yml
    secrets:
      sfdx_url: ${{ secrets.SIT_SFDX_URL }}
