name: Prod Deploy
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/Deploy.yml
    with:
      sfdx_url: ${{ secrets.PROD_SFDX_URL }}
    secrets: inherit
