name: Prod Deploy
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: jfgarcia268/vlocity_sfdx:latest
    steps:  
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ./.github/workflows/Deploy.yml
      with:
        sfdx_url: ${{ secrets.PROD_SFDX_URL }}
