name: Test

on:
  push:
    branches: [ test ]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: jfgarcia268/vlocity_sfdx:test
    steps:  
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Test   
      run: |
        export HOME=/root
        sfdx acumen:api:get